---
title: "Phenotype Analysis"
date: "03/03/2021"
output: pdf_document
---

# PentaTech
# Group Members
1. Manreet Kaur
2. Chirag Arora
3. Birti Kaur
4. Nafis Ahmed
5. Yajing Zhou


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, warning=FALSE, message=FALSE}
library(ggplot2)
library(tibble)
library(tidyr)
library(tidyverse)
library(utils)
```

```{r loading file}
Phenotypes_subset <- read.csv("Phenotypes_subset.csv")
head(Phenotypes_subset)
```

```{r plot0}
# Frequencies phenotypic abnormalities in human diseases
Frequency_of_abnormalities <- group_by(Phenotypes_subset, HPOFrequency0) %>%
                              summarize(N = n(), .groups = "drop_last")
Plot <- ggplot(data = Frequency_of_abnormalities,
               mapping = aes(x = HPOFrequency0,
                             y = N,
                             fill = HPOFrequency0))
Plot + geom_col(position = "dodge") +
       labs(x = NULL, y = "Count") +
       guides(fill = FALSE) +
       coord_flip() +
       geom_text(aes(label = N, hjust = -0.2)) +
       ylim(NA, 1700)
```

```{r loading file2}
library(dplyr)
AlexanderDisease <- read.csv("Associated_Phenotypes_With_AlexanderDisease.csv")
AlexanderDisease <- AlexanderDisease %>% slice(1:61)
head(AlexanderDisease)
```

```{r subset, warning=FALSE}
# Frequencies phenotypic abnormalities in human diseases
Frequency_of_abnormalities <- group_by(AlexanderDisease, HPOFrequencies) %>%
                              summarize(N = n(), .groups = "drop_last")
Frequency_of_abnormalities 
```

```{r SubsetPlot}
# Frequencies phenotypic abnormalities in human diseases
Plot <- ggplot(data = Frequency_of_abnormalities,
               mapping = aes(x = HPOFrequencies,
                             y = N,
                             fill = HPOFrequencies))
Plot + geom_col() +
       labs(x = NULL, y = "Count") +
       guides(fill = FALSE) +
       coord_flip() + 
       geom_text(aes(label = N, hjust = -0.2)) +
       ylim(NA, 25)
```

```{r SubsetPlot2}
# Frequencies phenotypic abnormalities in human diseases
Plot <- ggplot(data = AlexanderDisease,
               mapping = aes(x = HPOFrequencies, y = HPOTerms, color = HPOFrequencies))
Plot + geom_point() + 
       guides(color = FALSE) +
       geom_text(mapping = aes(label = HPOTerms)) +
       theme(axis.text.y = element_blank(), axis.ticks.y = element_blank())
```